export const GET_CONTACT = 'GET_CONTACT';
export const GET_CONTACT_SUCCESS = 'GET_CONTACT_SUCCESS';
export const GET_CONTACT_FAILED = 'GET_CONTACT_FAILED';

export const ADD_CONTACT = 'ADD_CONTACT';
export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS';
export const ADD_CONTACT_FAILED = 'ADD_CONTACT_FAILED';

export const SET_CONTACT = 'SET_CONTACT';
export const CLEAR_CONTACT = 'CLEAR_CONTACT';

export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';
export const UPDATE_CONTACT_FAILED = 'UPDATE_CONTACT_FAILED';

export const DEL_CONTACT = 'DEL_CONTACT';
export const DEL_CONTACT_SUCCESS = 'DEL_CONTACT_SUCCESS';
export const DEL_CONTACT_FAILED = 'DEL_CONTACT_FAILED';